(function() {var implementors = {
"ascii":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"ascii/struct.AsciiStr.html\" title=\"struct ascii::AsciiStr\">AsciiStr</a>",1,["ascii::ascii_str::AsciiStr"]]],
"bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bytes/buf/struct.UninitSlice.html\" title=\"struct bytes::buf::UninitSlice\">UninitSlice</a>",1,["bytes::buf::uninit_slice::UninitSlice"]]],
"serde_bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"serde_bytes/struct.Bytes.html\" title=\"struct serde_bytes::Bytes\">Bytes</a>",1,["serde_bytes::bytes::Bytes"]]],
"serde_json":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"serde_json/value/struct.RawValue.html\" title=\"struct serde_json::value::RawValue\">RawValue</a>",1,["serde_json::raw::RawValue"]]],
"wasmer_types":[],
"wasmparser":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"wasmparser/types/struct.KebabStr.html\" title=\"struct wasmparser::types::KebabStr\">KebabStr</a>",1,["wasmparser::validator::types::KebabStr"]]],
"wasmtime_environ":[],
"winnow":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"winnow/stream/struct.Bytes.html\" title=\"struct winnow::stream::Bytes\">Bytes</a>",1,["winnow::stream::Bytes"]],["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"winnow/stream/struct.BStr.html\" title=\"struct winnow::stream::BStr\">BStr</a>",1,["winnow::stream::BStr"]]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()