(function() {var implementors = {
"adler":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"adler/struct.Adler32.html\" title=\"struct adler::Adler32\">Adler32</a>"]],
"ahash":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"ahash/struct.AHasher.html\" title=\"struct ahash::AHasher\">AHasher</a>"]],
"crc32fast":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"crc32fast/struct.Hasher.html\" title=\"struct crc32fast::Hasher\">Hasher</a>"]],
"fnv":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"fnv/struct.FnvHasher.html\" title=\"struct fnv::FnvHasher\">FnvHasher</a>"]],
"fxhash":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"fxhash/struct.FxHasher64.html\" title=\"struct fxhash::FxHasher64\">FxHasher64</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"fxhash/struct.FxHasher.html\" title=\"struct fxhash::FxHasher\">FxHasher</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"fxhash/struct.FxHasher32.html\" title=\"struct fxhash::FxHasher32\">FxHasher32</a>"]],
"metrics":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"metrics/struct.KeyHasher.html\" title=\"struct metrics::KeyHasher\">KeyHasher</a>"]],
"seahash":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"seahash/struct.SeaHasher.html\" title=\"struct seahash::SeaHasher\">SeaHasher</a>"]],
"twox_hash":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"twox_hash/struct.XxHash64.html\" title=\"struct twox_hash::XxHash64\">XxHash64</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"twox_hash/struct.XxHash32.html\" title=\"struct twox_hash::XxHash32\">XxHash32</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"twox_hash/xxh3/struct.Hash128.html\" title=\"struct twox_hash::xxh3::Hash128\">Hash128</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.71.0/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"twox_hash/xxh3/struct.Hash64.html\" title=\"struct twox_hash::xxh3::Hash64\">Hash64</a>"]],
"wasmer_types":[],
"wasmtime_environ":[]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()